public enum FieldsToSort {
    BY_AVERAGE,
    BY_STRIKERATE,
    BY_4s_AND_6s,
    BY_STRIKERATE_WITHMOST_4sAND6s,
    BY_AVERAGE_WITH_STRIKE_RATE,
    BY_AVERAGE_WITH_MOST_RUNS,
    BY_TOP_BOWLING_AVERAGES,
    BY_TOP_BOWLING_STRIKING_RATES,
    BY_TOP_BOWLING_ECONOMY_RATES,
    BY_TOP_BOWLING_STRIKING_RATES_WITH_MOST_4Ws_AND_5Ws,
    BY_GREAT_AVERAGE_RATE_WITH_BEST_STRIKING_RATE,
    BY_MOST_WICKETS_WITH_GREAT_AVERAGE_RATE,
    BY_MOST_BATTING_AVERAGE_WITH_MOST_BOWLING_AVERAGE,
    BY_MOST_BATTING_RUNS_WITH_MOST_BOWLING_WICKETS;
}
